name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy isort
        
    - name: Check code formatting with Black
      run: |
        black --check --diff --color .
        
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
        
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
        
    - name: Type check with mypy
      run: |
        mypy --explicit-package-bases *.py --ignore-missing-imports --no-strict-optional
        
    - name: Check for common security issues
      run: |
        pip install bandit
        bandit -r . -f json || true

